# SpigotMessagePrinter by syncwrld #
#      www.github.com/syncwrld     #

options:
  # Delay between lines in seconds #
  delay-between: 0.5
  # Automatically center the text #
  center-text: true

default-actions:
  # When player join send a message #
  on-connect: 'welcome-to-server' # Leave empty for no message
  # When player disconnect send a message to the entire server #
  on-disconnect: 'goodbye-to-server'

messages:
  welcome-to-server:
    lines:
      - "&e$player, welcome to the server!"
      - "&eWe have many systems to you explore. Check it out:"
      - "&f‣ &eWarps (/warps) - Teleport to a warp"
      - "&f‣ &eMap (/map) - Open the server map"
      - "&f‣ &eSpawn (/spawn) - Teleport to the spawn"
      - "&f‣ &eHome (/home) - Teleport to your home"
      - "&f‣ &eHelp (/help) - Open the help menu"
      - "&f‣ &eSettings (/settings) - Open the settings menu"
      - "&f‣ &eRules (/rules) - Open the rules menu"
    sound: 'NOTE_PLING' # Leave empty for no song
    # If true, the sound will be played in every line printed - if false, it will be played only once when the first line is printed #
    play-sound-in-every-line: true
    # Delay between lines, in case of no delay set it to 0 (the value should be in seconds) #
    delay-between: 1
    # Send the message to all players in the server #
    send-to-all-players: false
  goodbye-to-server:
    lines:
      - "&e$player exit the server."
      - "&eThank you for playing with us!"
    sound: 'NOTE_PLING' # Leave empty for no song
    # If true, the sound will be played in every line printed - if false, it will be played only once when the first line is printed #
    play-sound-in-every-line: false
    # Delay between lines, in case of no delay set it to 0 (the value should be in seconds) #
    delay-between: 0
    # Send the message to all players in the server #
    send-to-all-players: true