name: message-printer
version: '1.0-SNAPSHOT'
main: me.syncwrld.messageprinter.MessagePrinterEngine
api-version: '1.13'

commands:
  printer:
    description: 'Prints a message'
    arguments:
      - message:
          description: 'The message to print'
          required: true